### ISSUE TITLE
Is CUDA implementation available

### ISSUE THREAD

**Issue by FengcunLi** [stanford-futuredata/stk#3]
The kernels in this repo are implemented in OpenAI Triton. I wonder whether you have a cuda implementation. Our LLM inference service is written in C++/CUDA（basically based on FasterTransformer）. A cuda implementation would be much easier to integrate MEGABLOCKS.

**Comment by tgale96** [comment]
Hi, the original sparse kernel implementation was done using CUTLASS. You can find them [here](https://github.com/tgale96/sputnik). We haven't maintained it since we switched to Triton so it is based on an older version of CUTLASS, only supports fp16 and is tuned for SM80 (A100).

There are a few other options you could try: 
(1) You could use CUTLASS grouped GEMM to compute a dMoE. We support this, in addition to the sparse dMoE implementation, in MegaBlocks. Our wrappers for these kernels are [here](https://github.com/tgale96/grouped_gemm).
(2) You could call cuBLAS GEMM in a loop, once for each expert. This will work ok as long as you have a low expert count per device (4-8ish). For higher expert counts per device you'll want a proper batched kernel via block-sparse matmul or grouped GEMM.

Let me know which of these sound attractive to you and I'm happy to provide more info!
